# JEKYLL SETTINGS
# ------------------------------------------------------------------------------
baseurl: "" # used for the navigation (keep blank)
exclude:
  - README.md
  - LICENSE.md
  - html
  # - elements.html

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed
  load_paths:
    - _sass
    - node_modules

# SITEMAP PLUGIN SETTINGS
# ------------------------------------------------------------------------------
defaults:
  -
    scope:
      path:            "pdf/*.pdf"
    values:
      sitemap:         false

# SEO PLUGIN SETTINGS
# ------------------------------------------------------------------------------
defaults:
  - scope:
      path: ""
    values:
      image: /img/global/default-og-image.jpg
# url: default.url.com
logo:
image: /img/global/default-og-image.jpg
title:
description:
author:
# categories: default categories
# social:
#   name: John Doe
#   links:
#     - https://twitter.com/johndoe
#     - https://www.facebook.com/john.doe
#     - https://www.linkedin.com/in/johndoe
#     - https://plus.google.com/+johndoe
#     - https://github.com/johndoe
#     - https://keybase.io/johndoe
# twitter:
#   username: johndoe
#   card: summary
# facebook:
#   app_id: 1234
#   publisher: 1234
#   admins: 1234
# webmaster_verifications:
#   google: 1234
#   bing: 1234
#   alexa: 1234
#   yandex: 1234
#   baidu: 1234
